# Generated by Django 4.2.7 on 2026-01-23 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("total_count", models.IntegerField(default=0)),
                ("avg_flowrate", models.FloatField(blank=True, null=True)),
                ("avg_pressure", models.FloatField(blank=True, null=True)),
                ("avg_temperature", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentTypeDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_type", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=0)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_distributions",
                        to="equipment.equipmentdataset",
                    ),
                ),
            ],
        ),
    ]
